---
name: release
on:
  push:
    tags:
      - "*"

jobs:

  release:

    name: Release
    runs-on: ubuntu-latest

    steps:

      - name: set up quemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:metabase-init"
          push: true
          tags: josesolisrosales/metabase-init:${{  github.ref_name }}