---
name: molecule

on:

  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * 5"

jobs:

  lint:

    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
